[theme]
theme = "gruvbox-dark"

[icons]
icons = "none"

[[block]]
block = "pomodoro"
notify_cmd = "notify-send '{msg}'"
blocking_cmd = false
message = "Take a break!"
break_message = "Back to work!"

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization $frequency"
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "sound"

[[block]]
block = "bluetooth"
mac = "98:09:CF:CE:36:08"
format = ""

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "battery"
format = "$percentage"
interval = 30

